#
#
## =========================================================
## DATABASE
## =========================================================
#
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#
## =========================================================
## SERVER
## =========================================================
#
#server.port=${PORT:8081}
#server.address=0.0.0.0
#
#
## =========================================================
## BREVO EMAIL API
## =========================================================
#
#brevo.api.key=${BREVO_API_KEY}
#brevo.sender.email=${BREVO_SENDER_EMAIL}
#
#
## =========================================================
## RAZORPAY
## =========================================================
#
#razorpay.key.id=${RAZORPAY_KEY_ID}
#razorpay.key.secret=${RAZORPAY_KEY_SECRET}
#
#
## =========================================================
## GOOGLE MAPS
## =========================================================
#
#google.maps.api-key=${GOOGLE_MAPS_API_KEY}



# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/car_rental_system
spring.datasource.username=root
spring.datasource.password=Aaryan@1401

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =========================================================
# SERVER
# =========================================================

server.port=8081
server.address=0.0.0.0


# =========================================================
# GMAIL SMTP
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=g4golden1401@gmail.com
spring.mail.password=buhsfmmonxgvbbvi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


BREVO_SENDER_EMAIL=g4golden1401@email.com
brevo.api.key=xkeysib-03909d8f6a56e8382ef5183b8b8493a6ce8fc95c001eabe87974b436aadad5e5-AyOwyhRi2U3ggxYiback

# =========================================================
# RAZORPAY
# =========================================================

razorpay.key.id=rzp_live_CQoQYjld6cBGWf
razorpay.key.secret=VRX8M9EJtN5DqWIGBdQiF0T3


# =========================================================
# GOOGLE MAPS
# =========================================================

google.maps.api-key=AIzaSyDwA6mql43n-gQq_VtnpbMN9QnsLOONyMs