
spring.datasource.url=jdbc:mysql://localhost:3306/car_rental_system
spring.datasource.username=qwertyuiop
spring.datasource.password=asdfghjkl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# ===========================
# EMAIL CONFIGURATION
# ===========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=123445@gmail.com
spring.mail.password=xxxxxxxxxxxxxxxxxxxx
  #YOUR_16_DIGIT_APP_PASSWORD

# =========================================================
# RAZORPAY TEST MODE
# =========================================================

razorpay.key.id=111111111111111111
razorpay.key.secret= 222222222222222222222

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.maps.api-key=xxxxxxxxxxxxxxxxxxxxxxxxxx
